baseURL = "www.example.com"
languageCode = "en-us"
title = "Bridge To Success"

[params]
google_analytics_id = "G-B37JDT0L7F"
google_tag_manager_id = ""

  [params.homepage]
  show_call_box = true
  hide_view_all_services = true

  [params.logo]
  mobile = "images/royal-potato.png"
  desktop = "images/logo2.png"
  desktop_height = "60px"
  alt = "Bridge To Success"

  [params.homepage_meta_tags]
  meta_description = "Bathinda’s premier tuition center for next generation of builders and makers"
  meta_og_title = "Bridge To Success"
  meta_og_type = "website"
  meta_og_url = "https://bridgetosuccessonline.com"
  meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-serif-theme/master/images/tn.png"
  meta_og_description = "Bathinda’s premier tuition center for next generation of builders and makers."
  #meta_twitter_card = "summary"
  #meta_twitter_site = "@zerostaticio"
  #meta_twitter_creator = "@zerostaticio"

  [params.team]
  summary_large_truncate = 120

  [params.footer]
  copyright_text = 'Bridge To Success © 2021'

#[[menu.main]]
#name = "Classes"
#url = "/classes/"
#weight = 1

[[menu.main]]
name = "Team"
url = "/team/"
weight = 2

[[menu.footer]]
name = "Home"
url = "/"
weight = 1

[[menu.footer]]
name = "Contact"
url = "/contact/"
weight = 2
